:PROPERTIES:
:ID:       527ED751-692C-40F8-B42C-C7D93B0D9DE0
:END:
#+TITLE: ansible

* 目录                                                    :TOC_4_gh:noexport:
- [[#ad-hoc][Ad-Hoc]]
- [[#pattern][Pattern]]
- [[#inventory][Inventory]]
- [[#playbook][Playbook]]
- [[#handlers][Handlers]]
- [[#tags][Tags]]
- [[#roles][Roles]]
- [[#本地执行][本地执行]]

* Ad-Hoc
  命令格式：
  #+begin_example
    ansible [pattern] -m [module] -a "[module options]"
  #+end_example

  ansible 默认会读取位于 =/etc/ansible/hosts= 作为 inventory，也可以使用 =-i= 选项指定 inventory 文件。

  常用模块：
  #+begin_src sh
    # run shell command
    ansible all -m shell -a 'echo $TERM'
  #+end_src

  参考：[[https://docs.ansible.com/ansible/latest/user_guide/intro_adhoc.html][Introduction to ad hoc commands — Ansible Documentation]]

* Pattern
  |------------------------+------------------------------+-----------------------------------------------------|
  | Description            | Pattern(s)                   | Targets                                             |
  |------------------------+------------------------------+-----------------------------------------------------|
  | All hosts              | all (or *)                   |                                                     |
  | One host               | host1                        |                                                     |
  | Multiple hosts         | host1:host2 (or host1,host2) |                                                     |
  | One group              | webservers                   |                                                     |
  | Multiple groups        | webservers:dbservers         | all hosts in webservers plus all hosts in dbservers |
  | Excluding groups       | webservers:!atlanta          | all hosts in webservers except those in atlanta     |
  | Intersection of groups | webservers:&staging          | any hosts in webservers that are also in staging    |
  |------------------------+------------------------------+-----------------------------------------------------|

  需要有 inventory 文件才行。

* Inventory
  Ansible Inventory 就是一个 INI 格式的配置文件，通过 group 来区分不同的 host，默认分组是 all 和 ungrouped，ungrouped 指只在 all 分组下面的 host，每个分组、每个 host 可以单独配置变量。

  而 host 可以存在于不同的分组，不同分组配置的变量会按优先级合并：all group > parent group > child group > host，同级分组间的优先级按照分组名称的 ASCII 排序。

  例子：
  #+begin_src conf
    [all:vars]
    
    variable_a=1
    variable_b=1
    variable_c=1
    
    [all]
    
    192.168.0.[1:10]     # 192.168.0.1..192.168.0.10
    192.168.0.[11:20:2]  # 192.168.0.11、192.168.0.13、192.168.0.19
    
    [all:children]
    
    subgroup
    
    [subgroup:vars]
    
    variable_a=2
    
    [subgroup]
    
    192.168.0.1 variable_a=3
    192.168.0.2
  #+end_src

  上面这个例子中，对于 192.168.0.1 来说 variable_a 的值是 3，192.168.0.2 的值是 2，其他的都是 1。

  除了自定义变量外，ansible 自身也有一些变量决定怎么访问 remote host，常用的几个：
  |------------------------------+-----------------------------------------------------------------------------|
  | 变量                         | 作用                                                                        |
  |------------------------------+-----------------------------------------------------------------------------|
  | ansible_connection           | 访问远程主机的方式，值可以是 ssh、smart、paramiko，默认值是 smart，常用 ssh |
  | ansible_user                 | 访问时使用的 user                                                           |
  | ansible_password             | 访问时使用的密码                                                            |
  | ansible_ssh_private_key_file | 访问时使用的 ssh key                                                        |
  |------------------------------+-----------------------------------------------------------------------------|

  参考：[[https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html][How to build your inventory — Ansible Documentation]]

  也可以在 =group_vars= 或 =host_vars= 目录中管理 Inventory 配置，参考 [[https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#organizing-host-and-group-variables][Organizing host and group variables]]。
  
* Playbook
  在 Playbook 中，hosts 可以按照 Pattern 匹配目标 host，通常，我们可以将目标 hosts 作为变量传入：
  #+begin_example
    ansible-playbook -v -i inventory -e "hosts={pattern}" play.yaml
  #+end_example

  #+begin_src yaml
    ---
    - hosts: "{{ hosts }}"
  #+end_src

  这样，每次执行的时候可以根据 pattern 指定要在哪些 host 上执行，比如某个 ip，某个分组，等。

  play 中，还可以使用各种条件来判断是否要在当前 host 上执行，比如：
  #+begin_src yaml
    ---
    - hosts: "{{ hosts }}"
    
      tasks:
    
      - name: do something
        shell: xxxx
        when: {{ var }}
    
  #+end_src

  在 host 属于某个分组时执行：
  #+begin_src yaml
    when: inventory_hostname in groups["<group name>"]
  #+end_src

  更多的根据特性执行某个任务，可以使用 roles 功能。

* Handlers
  在 playbook 中 handlers 是和 tasks 平行的一级，handlers 中的任务默认不会执行，而是需要 tasks 中的 task *changed* 后 notify 对应的 handler 任务执行：
  #+begin_src yaml
    ---
    - name: Verify apache installation
      hosts: webservers
      vars:
        http_port: 80
        max_clients: 200
      remote_user: root
      tasks:
        - name: Ensure apache is at the latest version
          ansible.builtin.yum:
            name: httpd
            state: latest
    
        - name: Write the apache config file
          ansible.builtin.template:
            src: /srv/httpd.j2
            dest: /etc/httpd.conf
          notify:
          - Restart apache
    
        - name: Ensure apache is running
          ansible.builtin.service:
            name: httpd
            state: started
    
      handlers:
        - name: Restart apache
          ansible.builtin.service:
            name: httpd
            state: restarted
  #+end_src

  使用于需要 changed 后才执行的后置任务，比如修改端口配置后重启服务，如果端口配置是预期的就不重启。

  默认情况下 handlers 中的任务在所有 tasks 执行完后才会开始执行，当然也可以使用 meta 主动触发：
  #+begin_src yaml
    tasks:
      - name: Some tasks go here
        ansible.builtin.shell: ...
    
      - name: Flush handlers
        meta: flush_handlers
    
      - name: Some other tasks
        ansible.builtin.shell: ...
  #+end_src

  参考：[[https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html][Handlers: running operations on change — Ansible Documentation]]

* Tags
  可以为 playbook 中的任务设置 tag，然后执行时通过类似 =--tags [tag1, tag2]= 选择要执行的任务：
  #+begin_src yaml
    tasks:
    - name: Install the servers
      ansible.builtin.yum:
        name:
        - httpd
        - memcached
        state: present
      tags:
      - packages
      - webservers
    
    - name: Configure the service
      ansible.builtin.template:
        src: templates/src.j2
        dest: /etc/foo.conf
      tags:
      - configuration
  #+end_src

  参考：[[https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html][Tags — Ansible Documentation]]

* Roles
  根据一定的目录结构来组织管理大量的 playbook，ansible 按照一定的规则自动加载配置，渲染模板。

  参考：[[https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html][Roles — Ansible Documentation]]

* 本地执行
  #+begin_src sh
    ansible-playbook test.yaml
  #+end_src

  #+begin_src yaml
    ---
    - name: run local
      hosts: localhost
      connection: local
      tasks:
        ...
  #+end_src

