:PROPERTIES:
:ID:       F253B7B8-4F0E-4399-8D87-3BD75E6AD34A
:END:
#+TITLE: Prometheus

* remote_read & remote_write
  Prometheus 本身具备存储采集到的 Metrics 数据的能力，但也可以使用远程存储，比如其他的 [[id:7E3881DE-E84A-4047-B145-FB5B234C92F9][TSDB]] 实现，此时可以使用 remote_read 和 remote_write 指定远程存储：
  + Prometheus 支持通过 remote_read 指定远程存储，通过 Prometheus 查询指标时会汇总 remote_read 中指定的数据源数据
  + Prometheus 也支持通过 remote_write 将采集的 Metrics 写入到指定的远程存储，配合 remote_read 可以让 Prometheus 变成无情的读写机器，自身不存储数据

* scrape_config
  Prometheus 的一个强大功能就是可以通过 scrape_config 配置多个 job 来定时拉去 metrics 数据写入存储，抓去的目标 endpoint 可以使用 static_config 指定 target，
  也可以使用集成的服务发现能力来自动发现 endpoint。

  比如 kubernetes_sd_config 可以发现 k8s 中的资源对象，比如 node、pod、service 等，做服务发现时通常会有很多 label 用于筛选发现的目标，比如发现 k8s node 时：
  #+begin_quote
  Available meta labels:
  
  + __meta_kubernetes_node_name: The name of the node object.
  + __meta_kubernetes_node_provider_id: The cloud provider's name for the node object.
  + __meta_kubernetes_node_label_<labelname>: Each label from the node object.
  + __meta_kubernetes_node_labelpresent_<labelname>: true for each label from the node object.
  + __meta_kubernetes_node_annotation_<annotationname>: Each annotation from the node object.
  + __meta_kubernetes_node_annotationpresent_<annotationname>: true for each annotation from the node object.
  + __meta_kubernetes_node_address_<address_type>: The first address for each node address type, if it exists.
  #+end_quote

  我们可以使用 *relabel_configs* 来指定某个 label 的匹配规则（虽说是 label，但感觉更像是参数）。
  
  参考：
  + [[https://prometheus.io/docs/concepts/jobs_instances/][Jobs and instances | Prometheus]]
  + [[https://prometheus.io/docs/prometheus/latest/configuration/configuration/][Configuration | Prometheus]]

* 查询逻辑
  Prometheus 查询时有一个 =step= 参数，对 PromQL 表达式求值时：
  1. 对于 [start, end] 时间区间，从 start 开始，以 step 为长度，把时间区间分成若干段
  2. 对每个段进行求值

  比如：start=10,end=20,step=2，那么就会有 ts=10,ts=12,ts=14,ts=16,ts=18,ts=206 段，然后为这 6 个段进行求值。求值方式视乎表达式中 Time series selector 的类型而定。

  不同类型的逻辑：
  + Instant vector selector：从该段的 timestamp（含）往前找，取第一个找到的值。如果该段 timestamp 往前的 5 分钟范围内没有找到任何值，则该段无值。
  + Range vector selector：返回的是当前 timestamp 之前的 range duration 内的所有值。

  grafana 中 step 的值是动态计算得到的。

  参考：[[https://www.cnblogs.com/frankyou/p/16264399.html][详解Prometheus range query中的step参数 - FrankYou - 博客园]]

