:PROPERTIES:
:ID:       d933c274-8113-499f-9ba2-7b6405349866
:END:
#+TITLE: 关于正确处理人民内部矛盾的问题
#+filetags: :book:politics:

☞ [[https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-19570227.htm][关于正确处理人民内部矛盾的问题（一九五七年二月二十七日）]]

* 目录                                                    :TOC_4_gh:noexport:
- [[#两类不同性质的矛盾][两类不同性质的矛盾]]
- [[#关于百花齐放百家争鸣长期共存互相监督][关于百花齐放、百家争鸣、长期共存、互相监督]]

* 两类不同性质的矛盾
  在我们的社会里依然存在着两类社会矛盾，分别为敌我之间的矛盾和人民内部的矛盾。这是性质完全不同的两类矛盾。

  -----

  *人民和人民内部的矛盾*
  
  人民这个概念在不同的国家和各个国家的不同的历史时期，有着不同的内容。拿我国的情况来说：
  + 在抗日战争时期，一切抗日的阶级、阶层和社会集团都属于人民的范围，日本帝国主义、汉奸、亲日派都是人民的敌人。
  + 在解放战争时期，美帝国主义和它的走狗即官僚资产阶级、地主阶级以及代表这些阶级的国民党反动派，都是人民的敌人；一切反对这些敌人的阶级、阶层和社会集团，都属于人民的范围。
  + 在现阶段，在建设社会主义的时期，一切赞成、拥护和参加社会主义建设事业的阶级、阶层和社会集团，都属于人民的范围；一切反抗社会主义革命和敌视、破坏社会主义建设的社会势力和社会集团，都是人民的敌人。

  敌我之间的矛盾是对抗性的矛盾。人民内部的矛盾，在劳动人民之间说来，是非对抗性的；在被剥削阶级和剥削阶级之间说来，除了对抗性的一面以外，还有非对抗性的一面。

  一般说来，人民内部的矛盾，是在人民利益根本一致的基础上的矛盾。在我国现在的条件下，所谓人民内部的矛盾，包括：
  + 工人阶级内部的矛盾，农民阶级内部的矛盾，知识分子内部的矛盾，工农两个阶级之间的矛盾，工人、农民同知识分子之间的矛盾，工人阶级和其它劳动人民同民族资产阶级之间的矛盾，民族资产阶级内部的矛盾，等等。
  + 国家利益、集体利益同个人利益之间的矛盾，民主同集中的矛盾，领导同被领导之间的矛盾，国家机关某些工作人员的官僚主义作风同群众之间的矛盾。

  -----

  *专政和民主和自由*
  
  我们的国家是工人阶级领导的以工农联盟为基础的人民民主专政的国家。专政的作用为：
  1. 压迫国家内部的反动阶级、反动派和反抗社会主义革命的剥削者，压迫那些对于社会主义建设的破坏者，就是为了解决国内敌我之间的矛盾。
  2. 就是防御国家外部敌人的颠覆活动和可能的侵略。
     
  专政的制度不适用于人民内部。人民自己不能向自己专政，不能由一部分人民去压迫另一部分人民。

  关于民主和自由：
  + 所谓有公民权，在政治方面，就是说有自由和民主的权利。但是这个自由是有领导的自由，这个民主是集中指导下的民主，不是无政府状态。无政府状态不符合人民的利益和愿望（[[id:056dc7c9-b518-4fc1-bcb4-4092684c23de][马克思主义和无政府主义]]）。
  + 实际上，世界上只有具体的自由，具体的民主，没有抽象的自由，抽象的民主。要求抽象的自由、抽象的民主的人们认为民主是目的，而不承认民主是手段。民主这个东西，有时看来似乎是目的，实际上，只是一种手段。
  + 民主自由都是相对的，不是绝对的，都是在历史上发生和发展的。在人民内部，民主是对集中而言，自由是对纪律而言。这些都是一个统一体的两个矛盾着的侧面，它们是矛盾的，又是统一的，我们不应当片面地强调某一个侧面而否定另一个侧面。
  + 在人民内部，不可以没有自由，也不可以没有纪律；不可以没有民主，也不可以没有集中。
  + 这种民主和集中的统一，自由和纪律的统一，就是我们的民主集中制。在这个制度下，人民享受着广泛的民主和自由；同时又必须用社会主义的纪律约束自己。

  我们主张有领导的自由，主张集中指导下的民主，这在任何意义上都不是说，人民内部的思想问题、是非的辨别问题，可以用强制的方法去解决。
  企图用行政命令的方法，用强制的方法解决思想问题，是非问题，不但没有效力，而且是有害的。我们不能用行政命令去消灭宗教，不能强制人们不信教。不能强制人们放弃唯心主义，也不能强制人们相信马克思主义。
  凡属于思想性质的问题，凡属于人民内部的争论问题，只能用民主的方法去解决，只能用讨论的方法、批评的方法、说服教育的方法去解决，而不能用强制的、压服的方法去解决。

  人民为了有效地进行生产、进行学习和有秩序地过生活，要求自己的政府、生产的领导者、文化教育机关的领导者发布各种适当的带强制性的行政命令。
  没有这种行政命令，社会秩序就无法维持，这是人们的常识所了解的。这同用说服教育的方法去解决人民内部的矛盾，是相辅相成的两个方面。
  
* 关于百花齐放、百家争鸣、长期共存、互相监督
  艺术上不同的形式和风格可以自由发展，科学上不同的学派可以自由争论。利用行政力量，强制推行一种风格，一种学派，禁止另一种风格，另一种学派，我们认为会有害于艺术和科学的发展。艺术和科学中的是非问题，应当通过艺术界科学界的自由讨论去解决，通过艺术和科学的实践去解决，而不应当采取简单的方法去解决。为了判断正确的东西和错误的东西，常常需要有考验的时间。

  对于科学上、艺术上的是非，应当保持慎重的态度，提倡自由讨论，不要轻率地作结论。

  对于非马克思主义的思想，应该采取什么方针呢?对于明显的反革命分子，破坏社会主义事业的分子，事情好办，剥夺他们的言论自由就行了。对于人民内部的错误思想，情形就不相同。禁止这些思想，不允许这些思想有任何发表的机会，行不行呢?当然不行。
  对待人民内部的思想问题，对待精神世界的问题，用简单的方法去处理，不但不会收效，而且非常有害。不让发表错误意见，结果错误意见还是存在着。
  而正确的意见如果是在温室里培养出来的，如果没有见过风雨，没有取得免疫力，遇到错误意见就不能打胜仗。因此，只有采取讨论的方法，批评的方法，说理的方法，才能真正发展正确的意见，克服错误的意见，才能真正解决问题。

