:PROPERTIES:
:ID:       dbcb0f06-b0ed-4b79-8021-0a7ff74b9bd3
:END:
#+TITLE: 唯物辩证法大纲
#+filetags: :philosophy:

《唯物辩证法大纲 - 李达》 

* 目录                                                    :TOC_4_gh:noexport:
- [[#哲学的基本问题][哲学的基本问题]]
  - [[#第一方面][第一方面]]
  - [[#第二方面][第二方面]]
- [[#辩证法与形而上学][辩证法与形而上学]]
- [[#研究的对象和一般特征][研究的对象和一般特征]]
- [[#物质运动空间与时间][物质、运动、空间与时间]]
- [[#世界的物质的统一性和发展的无限性][世界的物质的统一性和发展的无限性]]
- [[#唯物辩证法的规律][唯物辩证法的规律]]
  - [[#对立统一规律][对立统一规律]]
  - [[#量变质变规律][量变质变规律]]
    - [[#质量度][质、量、度：]]
    - [[#量变和质变][量变和质变]]
    - [[#飞跃的形式][飞跃的形式]]
  - [[#肯定否定规律][肯定否定规律]]
  - [[#唯物辩证法的诸成对范畴][唯物辩证法的诸成对范畴]]
- [[#当作认识论和逻辑学看的唯物辩证法][当作认识论和逻辑学看的唯物辩证法]]
- [[#读后感][读后感]]

* 哲学的基本问题
  哲学的基本问题是思维与存在的关系，分为两个方面：
  1. 第一方面：思维与存在何为第一性的问题，唯物论认为存在是第一性的，思维是第二性的，唯心论与之相反
  2. 第二方面：思维能否正确地认识存在的问题，可知论认为思维能正确地认识存在，不可知论与之相反

** 第一方面
   唯物论认为存在是第一性的，物质决定意识，唯物辩证法相较于旧的唯物论进步的一点是：旧的唯物论在历史观上认为少数人决定了历史的走向，唯物辩证法纠正了这一错误的观点，认为社会存在决定社会意识。
   历史并不是由少数人决定的。这也被叫做历史唯物论。

   唯心论可以分为客观唯心论和主观唯心论两种：
   + 客观唯心论认为宇宙中存在一个「绝对意志」，世界上的一切都是这个绝对意志决定的
   + 主观唯心论认为客观世界是不存在的，存在的只是“我”的感觉、观念

   唯心论是错误的，但唯心论存在自身的认识论根源：
   1. 人们的意识是客观世界的主观映像，是被移植于人脑中并在人脑中被改造过的物质现象。意识的内容和泉源是客观的，意识的形式是主观的。当人们把认识过程中的「感觉」夸大为脱离物质的东西时，就是主观唯心论。
      当人们把认识过程中的「概念」夸大为脱离物质的东西时，就是客观唯心论。
   2. 人们对客观世界的反映是积极的，能动的，能够运用到改造客观世界当中。如果把意识的能动作用夸大到不受物质约束的程度，否定了意识是存在的反映，就会陷入唯心论。这是一切唯心论的共同基础。

** 第二方面
   思维能否正确地认识存在的问题，也叫做思维和存在的同一性问题。可知论认为思维能正确地认识存在，唯物论必然是可知论。辩证法唯物论相较于旧唯物论进步的是：
   1. 指出实践是思维和存在同一性的基础，实践是检验思维是否符合现实的唯一标准
   2. 将辩证法运用于唯物论。旧唯物论认为思维对存在的反映是僵死的、不动的、一次完成的。而实际上认识是不断加深的，是一个由浅到深的过程

   唯心论也有可知论，但最后往往会走到不可知论去。

* 辩证法与形而上学
  基于对发展的观点的不同可以分为辩证法与形而上学，辩证法认为事物是普遍联系的，事物是发展的，有量的变化也有质的变化，同时认为事物内部也存在矛盾，矛盾普遍存在。事物运动的根因源自事物内部。
  形而上学与之相反，认为事物是孤立的，静止的，内部也不存在矛盾。事物只有量的变化没有质的变化，同时将事物变化的原因归结为外部力量的推动。

  辩证法并不否定外部力量的作用，但认为外因只是事物变化的条件，外因只有通过内因起作用。

  典型的矛盾观点：
  1. 关于社会变化的原因：形而上学、庸俗进化论总是用地理环境、气候等外部因素来解释，不是从社会内部原因来解释
  2. 关于人性：形而上学认为人性从古至今都是一样的，没有变化。人性本恶、人性本贪便属于形而上学的观点。在唯物辩证法中认为人性是一切社会关系的总和，人性受到社会关系的影响。

* 研究的对象和一般特征
  哲学在最初的时候是当时一切知识的总和，即包含了世界观的问题，也包含了后来产生的专门学科研究的问题。随着生产斗争和阶级斗争的发展，越来越多的问题从哲学中分化出去成为专门的学科，比如数学、物理、化学、社会科学等等。
  最后，除了关于思维的学说（辩证法和形式逻辑，形式逻辑不属于哲学），其余一切关于自然和社会的学说都归属于各门实证科学之中了。

  但是各中专门科学都是研究特殊领域中的特殊规律的，不是研究世界最一般规律的。而唯物辩证法研究的便是关于外部世界和人类思维运动的一般规律的科学。

  考察发现一般规律在界所特有的表现就是自然辩证法，在社会历史中特有的表现就是历史辩证法（唯物史观）。

  一般特征为：唯物论和辩证法的统一、科学的世界观和方法论的统一、理论和实践统一、阶级性和科学性统一。

* 物质、运动、空间与时间
  在辩证法唯物论中，物质的范畴为：离开意识而独立又能为意识所反映的「客观实在」。需要注意区分物质的范畴、物质的结构和物质的形态。物质的范畴是固定的，但对物质的结构的认识是不断加深的，物质的形态是不断变化的。

  关键的一点是：物质的物理特性和物质是否存在于意识之外是两个不同的问题。关于量子力学中的观察者效应和物质的统一性问题 ☞ [[id:7d86af39-ce4c-4f57-9cd7-6040734b583a][双缝干涉实验和观察者效应]]。

  而物质和运动是不可分割的，物质是运动的主体，而运动是物质的存在形式和固有属性。没有离开运动的物质，也没有离开物质的运动。运动是绝对的，静止是相对的。认为运动是主体的是[[id:d056a180-f9bc-428c-bbb6-9072e6907e5a][唯能论]]。

  运动的基本形式按照当前的科学水平可以分为：
  1. 客体在空间中的位置变动（这是力学的研究对象）
  2. 波和粒子的运动（这是物理学的研究对象)
  3. 原子的化合和分解运动（这是化学的研究对象)
  4. 有机体的运动，即同化与异化、遗传与变异（这是生物学的研究对象)
  5. 社会运动，即生产力和生产关系、基础和上层建筑的发展变化（这是社会科学的研究对象）

  这些运动形式不是彼此孤立，而是相互依存的：
  1. 高级运动形式依赖于低级运动形式，它是在低级运动形式的基础上产生、并把低级运动形式包括在自己之内。
  2. 低级运动形式当其作为高级运动形式的基础而被包括在高级运动形式之内时，它的作用也依赖于高级运动形式。
  3. 各种运动形式可以在一定的条件下互相转化。从宇宙发展的长河看，各种运动形式是按照由低级到高级，由简单到复杂的秩序逐步展开的。

  其次，各种运动形式固然是互相依存的，但又是本质上互相区别的。唯物辩证法不允许把不同质的运动形式混清起来，不允许把高级的运动形式归结为低级的运动形式。
  当然，高级运动形式总是包括着低级运动形式，但是低级运动形式在高级运动形式中并不起主导的、决定的作用，而只起辅助的、次要的作用。高级运动形式之所以为高级运动形式，并不是因为它包括着低级运动形式， 而是因为它具有自己的质的特殊性。

  [[https://zh.wikipedia.org/wiki/%E7%A4%BE%E4%BC%9A%E8%BE%BE%E5%B0%94%E6%96%87%E4%B8%BB%E4%B9%89][社会达尔文主义]]便是使用生物学的规律去解释社会现象得到的。

  同时，运动是守恒的，任何运动都不会从乌有中产生，也不会转化为乌有，客观存在着的是各种运动形式之间相互转化的无限过程：
  1. 任何一种运动形式在转化为别种运动形式的时候，运动的总量是不变的。这是这个原理的量的方面。
  2. 任何一种运动形式，都具有转化为别种运动形式的永不丧失的能力。这是这个原理的质的方面。

  这里不能只从数量上去把握，而且还必须从质量上去理解。

  而空间和时间是运动着的物质的存在形式，正像运动与物质是不可分割的一样，空间和时间与物质也是不可分割的：
  1. 没有离开空间和时间的物质。
  2. 没有离开物质的空间和时间。空间和时间是物质的存在形式，是以物质为内容的，相对论证明了空间和时间的待性也是随着物质形态的变化而变化的。

     绝对时空观：空间是贮藏物质的空虚的“容器”，时间是绝对均匀流逝的持续性，二者都是与物质过程无关的独立实体。空间和时间的特性是绝对不变的，空间的特性服从于欧几里得几何学，时间的特性则服从于数序规律。这样理解的空间和时间叫做“绝对空间”和“绝对时间”。
     而实际上相对论已经说明了空间和时间会受到物质的影响。

  同时，唯物辩证法认为物质世界是无限的，因而作为物质的存在形式的空间和时间也是无限的。宇宙无所谓边际，宇宙无所谓始终。如果承认空间和时间有限，那么边界外的就只能是非物质的东西了，就容易引入上帝的存在。比如时间的开始因为上帝啥的。

  PS: 这里得出空间和时间的无限性的方式感觉很牵强，虽然常识不一定正确，有限还是无限现在人类都没法证明。但如果承认有限，那么边界外的东西确实就很唯心了。

  而空间和时间的区别在于，它们是物质的两种不同的存在形式，空间是三维的，时间是一维的。

  PS: 书中这里不承认多维空间。感觉这篇文章[[https://zhuanlan.zhihu.com/p/59497506][科学解读：什么是时间？什么是空间？理论上时空是什么？ - 知乎]]里的定义更好：
  + 时间就是量子尺度上可计数的状态变化
  + 空间就是物质变化的呈现
  + 时间与空间都是源于物质的变化，于是时间与空间，就（通过物质变化）一起构成了——紧密联系不可分割的时空，并且时空与物质，就像是一个统一的整体，是一个共同的本质，所呈现的不同表象。

* 世界的物质的统一性和发展的无限性
  物质的统一性：
  1. 整个自然界，从宏观世界到微观世界，从无机世界到有机世界，都是统一于物质的。
  2. 人类社会是物质世界的高级发展阶段，唯物史观指出，人类社会的基础是人们在生产物质生活资料的过程中所结成的生产关系。这种生产关系是不依任何人的意识为转移的物质的关系。

  发展的无限性：
  1. 一切现存的事物，包括人们的意识在内，都是这个统一的物质世界长期发展的产物；物质世界的发展不是简单的循环和重复，而是由低级到高级、由简单到复杂的无限过程。

  意识是物质世界发展到一定阶段的产物：
  1. 由低级的反映形式到高级的反映形式的发展，从无机的物理或化学的反映，到生物对刺激的反映，到非条件反射和条件反射。
  2. 意识是人脑的机能，除了接受现实刺激物的刺激而引起条件反射的一套神经活动，还有更高级的接受语言刺激而引起条件反射的一套神经活动。从感性认识到概念认识。语言是思维的直接现实，是思维的自然物质。
     意识决不是什么同物质并列的独立的实体，更不是物质世界的创造主；恰恰相反，它仅仅是物质世界发展到一定阶段的产物，仅仅是一种特殊的物质（人脑）的机能或属性，仅仅是物质世界在人脑中的反映，它是一点也不能离开物质的。
  3. 意识对物质世界有反作用，但意识的能动作用不管有多么大，仍然不能不受物质世界的制约，不能超越客观物质条件所许可的范围。

  核心的观点就是：
  1. 物质决定意识，意识是物质的。延展到社会学就是生产力决定生产关系，经济基础决定上层建筑。意识有主观能动性，但也受限于物质基础。
  2. 物质是发展的，形而上的观点，不变或者只有量变没有质变是错误的。

* 唯物辩证法的规律
  物质世界的各个特殊领域中的现象的发展变化都服从于各自的特殊规律，而整个物质世界的发展变化又服从于一般规律，即普遍规律。前者是各门具体科学的研究对象，后者是唯物辩证法的研究对象。

  任何事物不仅受普遍规律的支配，而且受特殊规律的支配。只懂得普遍规律而不懂得特殊规律，还是不能把具体工作做好。如果以为一个人只要学了唯物辩证法的规律，就既会种地，又会做工，既会打仗，又会治病，成为无所不能的万事通，那是错误的。

  唯物辩证法不是包医百病的现成药方，而是指导我们研究具体事物的工具。

** 对立统一规律
  ☞ [[id:3c6d6981-2f4a-42b8-8f80-5da12b25bdc6][矛盾论]]

  1) 对立统一规律是辩证法最根本的规律，其他辩证法的规律和范畴都是对立统一规律在不同方面的表现形态
  2) 唯物辩证法从来不把矛盾的同一性解释为矛盾双方的“共同点”或“共同要求”，也从来不把矛盾双方的同一性说成只是不可分离地联系着的意思，相反，它认为矛盾同一性的更加重要的意义是矛盾双方能够而且必然在一定的条件下向着自已对方所处的地位转化（也就是事物能够质变）

** 量变质变规律
   量变质变规律是对立统一规律的具体表现形态之一。这个规律表明，事物的发展是在由量变到质变、又由质变到量变的无限交替过程中实现的。

*** 质、量、度：
    质是什么：质就是一个事物区别于其他事物的特殊的内在的规定性。是同事物联系在一起的，没有脱离事物的质，也没有脱离质的事物。物的质是人们认识事物的客观基础。进行任何工作都必须注意事物的质的区别。

    任何事物的质既是一个统一的整体，又具有许多不同的方面。在这个意义上，我们可以说一个事物有许多方面的质。例如人这个事物的质，就有社会的方面和生理的方面。

    -----

    质由事物内部所包含的特殊矛盾决定：
    #+begin_quote
    任何运动形式，其内部都包含着本身特殊的矛盾。这种特殊的矛盾，就构成一事物区别于他事物的特殊的本质。这就是世界上诸种事物所以有千差万别的内在的原因，或者叫做根据。（矛盾论）
    #+end_quote

    一个比较复杂的事物，其内部包含着多种矛盾。每一种矛盾都决定着这个事物的质的一定方面。但是，如对立统一规律所指出的，这些矛盾的地位和作用并不是平列的，有根本矛盾和非根本矛盾的区别。为根本矛盾所决定的，是质的根本的方面，为非根本矛盾所决定的，是质的非根本的方面。根本矛盾是贯串于事物发展过程的始终，并且规定着或影响着其他矛盾的，因此，为根本矛盾所规定的事物的质的根本方面也必然与事物的发展过程相始终，并且规定着和影响着质的非根本的方面。
    非根本矛盾则不一定贯串于事物发展过程的始终，而可以在事物发展的中途发生或解决；即令贯串于过程的始终，也总是受着根本矛盾的规定或影响，对于某事物之所以为某事物没有决定的意义。

    -----

    质与属性的关系：属性是事物的质在同别种事物发生关系时的表现。同一种质可以表现为许多属性。

    任何事物的属性都是极其多样的，但是无论哪一种属性都是质的表现。事物有什么样的质，就必然会有什么样的属性；事物的质改变了，为这种质所规定的属性也就必然随着消失。质与属性是统一的。但是，质与属性的统一不是机械的直接的等同，而是充满矛盾的辩证的统一。

    属性虽然是质的表现，但并不是所有的属性都一下子表现出来。有些属性在事物的一定发展阶段表现出来，在另一发展阶段却隐蔽起来了；有些属性在事物的一定发展阶段潜伏着，在另一发展阶段却表现出来了。

    我们只能通过事物的属性去认识事物的质。但是，既然只有在事物同事物发生关系的时候，只有在事物的运动过程中，事物的属性才能充分地显示出来，那么，为了正确地认识事物的质，就应当在事物的各种特定关系中、在事物的运动过程中来全面地认识事物的属性。

    -----

    事物除了质的规定性以外，还有量的规定性。量是标志质的范围和等级的范畴。

    量和质虽然都是事物的不可缺少的规定性，但是二者是互相对立的。质与事物的存在是直接同一的，某物失去了自己的质就不再成其为某物；量与事物却没有直接的同一性，在一定的范围内，量的增减并不影响某物之为某物。因此，如果把质叫做事物的内在的规定性的话，那么，也可以把量叫做事物的外在的规定性。

    量和质是对立的，又是统一的。首先，量和质是互相联系的。任何质总是具有一定量的质，任何量也总是具有一定质的量。在研究问题的时候可以单单研究事物的质的方面或者量的方面，而把另一方面暂时撇开不管；但是，在现实中，离开质的量和离开量的质都是不存在的。其次，量和质还在一定的条件下互相转化。

    在考察事物的量的规定性的时候，应当区别外延的量和内涵的量。
    + 外延的量是质的存在范围的标志，是质的广度的标志。例如，体积、重量、个数等等，就属于外延的量。外延的量是可以用机械的方法来计算它们的代数和的。例如一吨铁加一吨铁等于两吨铁，五十公升水加五十公升水等于一百公升水等等。
    + 内涵的量则是质的等级的标志，是质的深度的标志。例如温度的高低、颜色的深浅、金属的硬度、生命的长短、劳动生产率的高低等等，就属于内涵的量。内涵的量是不能用机械的方法来计算它们的总和的。例如两个温度为五十度的物体加在一起并不等于一百度，五十个人各做一个习题并不等于一个人做五十个习题。

   对量的认识不能脱离对质的认识。只有在认识事物的质的基础上，认识事物的量才有实际意义。

   对于事物的认识固然首先要注意质的方面，但是在认识事物的质的基础上对事物的量的方面进行分析或估计，也是不可忽视的。因为：
   1. 只有正确地把握了事物的量，才能更深刻地把握事物的质。
   2. 只有正确地把握了事物的量，才能正确地估计这个事物在实践中的地位和作用。

   -----

   事物的质和量的统一，不仅一般地表现在质总是具有一定量的质，量总是一定质的基础上的量；尤其深刻地表现在任何事物都有保持它的质的数量界限。这种使事物能够保持某种特定的质的量的界限，在哲学上就叫做度。

   事物在处在相对稳定状态的时候，它的量的变化是没有突破一定的度的。但是，这仅仅是一种暂时的情形。事物在内部矛盾的推动之下，总是朝着突破度的方向发展；发展的结果，终于会突破一定的度，使事物原有的质变成另一种质。

*** 量变和质变
    量变和质变是由事物内部的矛盾斗争所引起的两种运动状态。

    当事物内部的矛盾双方的斗争还没有达到主次易位的程度时，当事物的度还没有被突破、因而还保持着质的相对稳定性时，这时的变化就叫做量变；反之，当事物内部的矛盾双方的斗争已经使双方的主次地位开始发生变换时，当事物的度正在被突破，因而质的相对稳定性已开始丧失时，这时的变化就叫做质变。

    事物的发展过程，就是由量变到质变、由质变到量变的循环往复而又由低到高的无限过程。

    -----

    事物总是经历着由量变到质变的过程。由量变到质变的形式是多种多样的，大体说来，可以分成由数量的增减引起质变和由场所的变更引起质变这样两种形式。

    首先，单纯的数量增减，达到一定的程度就会引起质变。例如，元素原子核电荷数的增减，会使一种元素变为另一种元素。又如，由同样种类的原子构成的化合物，原子的数目不同，化合物的性质也就不同。

    其次，在有些情况下，尽管事物的数量并没有增减，但是构成事物的成分在排列的次序上发生了一定的变化（这也是量变的一种特殊形式)，也会引起质变。化学上的同分异构体和同素异性体就表明了这种情况。

    由于事物的质有许多方面，量也有许多方面，在分析量变如何引起质变的问题时，必须注意质和量的对应关系。一定的量变所引起的并不是随便一种质变，而仅仅是同它相对应的那种质变。

    例如，水的质既有物理的方面，也有化学的方面。水的物理方面的质是由水分子之间的凝聚力和排斥力的矛盾决定的，因此，这一对矛盾的斗争及其消长变化这样一种特定的量变，只能引起水的物理方面的质变，而不能引起水的化学方面的质变。
    水在一个标准大气压力下达到了镊氏 100 度，分子间的排斥力就超过凝聚力而跃居于矛盾的主要方面，水的物理的质就发生变化，由液体变成气体；但是水的化学的质并没有发生变化。
    反之，水的化学的质却是由水分子内部的氢原子和氧原子的特殊矛盾，即特殊的化学键所决定的（在水分子中两个氢原子各和氧原子共用一对电子，形成共价键)，只有当温度升高到使氢氧间的化学键发生分裂时，水的化学性质才会改变（需要摄氏 4000°一 5000°的高温）。

    -----

    事物在质变完成以后，就在新质的基础上开始新的量变。

    在新质基础上所产生的量变，同旧质基础上的量变是有根本区别的，并不是简单地回到原来的出发点。这是因为“量变改变事物的质和质变同样也改变事物的量”。一百个劳动者协作所能生产出来的产品，并不是简单地等于一百个劳动者单独生产时所能生产出来的产品的总和，而是要比这个总和大得多，并且能够达到单独生产时无法达到的产量。

    -----

    由于事物内部矛盾的复杂性和不平衡性，量变过程中质变和量变往往不是以纯粹的形式进行，而是互相错综的。在量变的过程中有部分的质变，在质变的过程中也有量的扩张。

    -----

    事物在发生根本质变以前，总的说来是处于量变过程中。但是，在总的量变过程中，却可以有部分的质变。部分的质变，大体上可以分为阶段性的部分质变和局部性的部分质变两种情形。

    这两种情形，都必须从事物内部矛盾的变化去说明。

    阶段性的部分质变，是事物在其内部的根本矛盾以及由此规定的事物的根本的质没有改变以前，在不同的发展阶段上显现出来的部分的质变。质变就是矛盾的主要方面和非主要方面的互易位置，即矛盾的解决。所以，在事物内部的根本矛盾没有解决以前，事物总的说来还处在量变过程中，还没有发生根本的质变。
    但是，复杂的事物内部还包含着非根本的矛盾。这些非根本的矛盾却在根本矛盾获得解决以前；有些是暂时地或局部地解决了，有些又发生了；而每一个非根本矛盾的解决或发生，就是一个部分的质变，就会使发展过程显现出阶段性。

    局部性的部分质变，是在事物的全部没有发生根本质变以前，在局部范围内显现出来的根本质变。在根本矛盾还没有在全局上解决以前，整个事物仍处在量变过程中，没有发生根本质变。但是，在这种情况下，事物的根本矛盾却可以在某些局部获得解决，从而导致这些局部的根本质变（这种对局部来说的根本质变，对全局来说仍只是部分质变)。

    简单来说就是：
    + 非根本矛盾的解决 - 量变中阶段性的部分质变
    + 局部根本矛盾的解决 - 量变中局部的部分质变

    部分质变同根本质变的界限在一定的范围内是绝对的。但是，由于事物范围的极其广大以及发展过程的无限性，二者的界限又有相对的一面：在一定场合下为根本质变的东西，在另一场合下则成为部分质变；反过来也是一样。究竟某一种具体变化应当看做根本质变还是分质变，要依研究的对象而定。

    *范围很重要。*

    -----

    不仅量变过程中有部分质变，而且质变过程中也有量的扩张。

    当事物的质变开始时，新质并不是同时在事物的全体上出现，而是在旧质的范围内首先突破一点或几点，然后在数量上迅速扩张，直到占领全盘，完成质变过程的。

    质变过程中的量的扩张，同量变是不同的。量变并不产生新质，而质变过程中的量的扩张则每一步都产生新质。

    质变过程中的量的扩张，同量变过程中的部分质变也是不同的。
    + 首先是同阶段性的部分质变不同。阶段性的部分质变，其根源不在事物根本矛盾的解决，因而并不影响事物的根本的质；而质变过程中量的扩张则是根本矛盾得到解决的过程，它的完成也就是事物根本质变的完成。
    + 其次，它也同局部性的部分质变不同。局部性的部分质变是在总的量变过程中发生的，这时事物的根本质变还没有开始，新质虽然已经在局部范围内出现，但是旧质还具有相对的稳定性，新质虽然也可能在量上有所增长，但还不能迅速占领事物的全盘；
      而质变过程中的量的扩张则是在事物的根本质变开始以后发生的，这时旧质的崩溃之势已成，新质将以迅猛的姿态占领全盘，完成根本质变。

    -----

    量变和质变的辩量变和质变证关系的概括说明：量变是质变的辩证关系的必要准备，质变是量变的必然结果。
    1. 首先，任何质变，都必须以一定的量变作为准备，才可能发生。
    2. 其次，任何量变的最后结果，必然是质变。

*** 飞跃的形式
    任何事物都要经历由量变到质变的过程，转变为另一种事物。质变就是从一种质到另一种质的飞跃。实际生活表明，一切事物都要通过飞跃才能完成质变，但是，飞跃的形式又是多种多样的。

    飞跃的形式是由事物内部矛盾的特殊性和事物所处的外部条件决定的。多种多样的飞跃形式，可以大体上区分为爆发式的飞跃和非爆发式的飞跃两种类型。对应对抗和非对抗的斗争形式。

    判断一个过程是不是飞跃，不能根据这个过程的长短，而只能根据具体事物内部的矛盾状况。只要事物内部的矛盾双方的原有联系还没有开始破裂，统一体还相对稳定地存在着，矛盾双方的主次地位还没有发生变化，那么，不管这种状态持续了多久，都是量变；
    反之，只要事物内部的矛盾双方的原有联系已开始破裂，统一体已开始分解，矛盾双方的主次地位已开始发生转化，那么，不管这种状态持续了多久，都是飞跃。

    只有首先根据事物内部的矛盾状况判定了过程是属于量变还是属于飞跃以后，再去估计它们所需要的时间才是有意义的。

** 肯定否定规律
   肯定否定规律是对立统一规律的具体表现形态之一。这个规律表明，事物发展的总趋势是前进的，而前进的道路是曲折的。

   简单来说，就是事物内部肯定因素和否定因素同时存在，事物发展在先肯定，后否定，然后否定之否定的过程中螺旋前进。其中，否定不是进化，不是改良，不是旧事物在新形式下的继续，而是质变，是革命，是旧事物的死亡和新事物的产生。其次，否定不是旧事物的一笔勾销，
   而是包含着继承的因素的。在否定中被消灭了的是旧事物的根本性质，至于旧事物中那些经过改造以后可以成为新事物的营养料的个别因素，却被新事物吸取过来，加以改造，作为新事物的有机成分而保留了下来。

   同时由总趋势是前进的这一结论得到，新事物是不可战胜的。而新事物的定义不是出现的晚就是新，而是只有同历史发展的客观要求相符合的、具有成长壮大的必然性的事物，才是新生事物。

   感想：
   1. 肯定否定的循环感觉是合符逻辑的，但总趋势是前进的这一点感觉不是很能信服。虽然说否定之否定后，新的肯定较最初的肯定有了新的变化，但「前进」这个概念怎么定义呢？
   2. 从人类历史来看，社会中各种事物的发展来看，总体趋势是前进的确实好像也没问题。但是论证逻辑感觉不能信服。
   3. 相关论证承认倒退存在，但强调总体趋势是前进的
   4. 本来想到了热寂说，但搜了一下，也有相关理论反驳了热寂说，比如「涨落」和「宇宙是负热容的不稳定系统」这两个

   总的来说，「前进」这个词感觉有比较强的主观情感，同时考虑到政治因素，感觉也带有比较强的政治目的。事物在肯定否定的循环中发展，至于总趋势是否是前进，而当前是前进还是倒退，感觉还是值得思考的问题。

** 唯物辩证法的诸成对范畴
   范畴是客观事物的本质联系在人们头脑中的反映，是人们认识世界过程中的支撑点和阶梯。人们在实践过程中，反复地接触到同一种类的事物，积累了关于某一种类事物的种种属性、特征、联系等等的丰富印象，于是就在头脑中进行整理和概括的工作，
   把这类事物的共同的本质联系抽象出来，造成概念，并在概念的基础上进行逻辑的思维活动。

   各门科学都有自己特有的范畴，这些范畴以简约的压缩的形式反映着本门科学所研究的特殊对象的特殊的本质联系。例如，在数学中有正数和负数、微分和积分，物理学中有质量和速度、粒子和场，生物学中有个体和种、同化和异化，政治经济学中有商品和货币、地租和利润，等等。

   唯物辩证法的范畴包括物质、意识、运动、量、质、肯定、否定等等。本质与现象、内容与形式、原因与结果、必然性与偶然性、可能与现实等范畴，则是对立统一规律的补充和具体化形态的主要的成对范畴。

   这几个范畴都基于对立统一规律来阐述，核心通过「决定事物的特殊矛盾」来界定，比如：
   + 本质和现象，本质对应事物本身包含的特殊矛盾，现象是本质的表现，是现象逐步展开的过程。现象包含真象和假象，真象同事物本质相一致，假象同事物本质相反，是事物本质派生出来的自身的对立物。
   + 内容和形式，内容是构成事物的一切内在要素的总和，形式就是这些内在要素的结构或表现。内容决定形式，形式反过来影响内容。比如生产力、生产关系。基于这样关系，观察处理问题先注意事物的内容，而不是搞形式主义。
   + 原因与结果，两者是对立统一的。
   + 必然性与偶然性，必然性是由事物内部的根本矛盾所规定的确定不移的趋势，偶然性是不被过程的根本矛盾所规定的可以移易的现象。偶然性通常来自过程内部的非根本的矛盾和其他过程对本过程的影响。两者是对立统一的，
     必然性只有通过大量的偶然现象才能表现出来，偶然性是必然性的表现形式和补充。其次，偶然性的背后总是隐藏着必然性，必然性是偶然性的支配力量。
   + 可能与现实，可能是由事物内部所包含的矛盾决定的，应该区分可能与现实，从现实出发。区分可能与不可能，避免白费力气。区分可能与抽象的可能，即存在这样的可能，但在事物发展的下一阶段不具备成为现实的条件。
     不要将遥远的可能拿到现在在实现，也不要忽视其存在。

* 当作认识论和逻辑学看的唯物辩证法
  整体是[[id:184069db-12a6-4805-973c-41a21e508eba][实践论]]的内容，多出来比较特别的是感性和理性认知的形式：
  + 感性认知的形式
    + 感觉 - 感觉是人们在实践中接触客观对象时最初发生的东西，是“意识和外部世界的直接联系”。比如视觉、触觉、味觉等等。
    + 知觉 - 感觉是客观对象的个别属性的反映。人们在取得各种感觉的基础上把这些感觉综合起来，形成关于客观对象的整个形象，就是知觉。
    + 表象 - 表象是曾经作用于感官的那些客观对象的形象的再现，也就是知觉的再现。表象的存在是不以客观对象直接作用于感觉器官为条件的。即使某种知觉已经消失了多年，也仍然可以在头脑中使它再现出来，形成表象。
  + 理性认知的形式
    + 概念 - 人们在反复的社会实践中，积累了丰富的感性概念材料，于是人们的头脑就对这些感性材料进行去粗取精、去伪存真、由此及彼、由表及里的改造和制作，抽象出贯串于其中的一般的本质的东西，并用一定的物质外壳即词把它标志起来，这就是概念。
    + 判断 - 判断是比较概念高级的思维形式。是展开的概念。比如定义概念 A，那么哪些事物是 A，哪些不是，需要通过判断来展开概念。
    + 推理 - 推理是比较判断更高级的思维形式，是由已有的判断过渡到新判断的理性活动。通过推理，人们可以扩大认识的成果，从现有的知识中推出新的知识，从已知推出未知。它不仅能反映出事物的现在的内部联系，而且能反映出事物的发展趋势。

* 读后感
  书是好书，各方面概念感觉都讲了下，确实有点大纲的意思。但是书中感觉还是有很多偏向政治正确的观点，不断强调唯物辩证法的正确性，其他唯心或形而上哲学的错误，虽然也不是不行，但篇幅确实多了点。

  不过考虑到时代背景，也可以理解。1965 年完成的讨论稿，1978 年由陶德麟遵李达遗愿作了修订，由人民出版社以《唯物辩证法大纲》的书名出版。

