:PROPERTIES:
:ID:       46b581a6-f083-4273-a19a-af46f9a09eea
:END:
#+TITLE: 家庭、私有制和国家的起源
#+filetags: :philosophy:

* 目录                                                    :TOC_4_gh:noexport:
- [[#家庭][家庭]]
- [[#国家][国家]]
- [[#世袭][世袭]]
- [[#脉络][脉络]]
- [[#摘抄][摘抄]]

* 家庭
  家庭形态和婚姻形式随着生产力和生产关系的发展而变化：
  1. 群婚，生产力低下，男女间生产力无大的差距。由于群婚下女性能够知道自己的子女是谁而男性不能，因此基于母系血缘关系的母权社会是这个时期的主要形态。
  2. 对偶制家庭，男子多个妻子中有一个主妻，而这个男子也是这个女子多个丈夫中主要的丈夫。书中认为这个形态的出现是因为女子的贞操观念，但个人认为更可能是随着近亲结婚的禁止，后代变得更健康强壮，
     男女间生产力开始出现差距。母权对父权做出了让步，让男子逐渐能够有自己能够确定的亲生子女。
  3. 专偶制家庭，随着生产力的进一步发展，男女间生产力差距变大，女性从社会公共事业中退出，成为男性的附属。母权社会全面转向父权社会。

  在现代，随着生产力的进一步发展，男女间生产力差距缩小，女性重新假如社会公共事业建设，女权主义，妇女解放运动随之展开。男女间组建家庭从基于经济利益变为基于感情。

  看法：
  + 经济基础决定上层建筑，过去随着生产力发展女性因为生理劣势丧失了经济上的话语权，而现在，生理劣势被更先进的生产力抹平，女性重新获得相应的权力。但这里的核心点在于，女性需要通过参加到社会生产当中来获取相应的社会地位。
  + 过去组建家庭，结婚生子主要出于「经济」上的考虑，一个主要表现就是结婚对象是家里长辈安排的，并没有感情基础。而现在，大部分人能够自己养活自己，组建家庭逐渐变得更关注「感情」因素，甚至，性别、数量都不在是硬性限制。
    一个例子就是现在社会上同性恋的变多，而且往往都是出现在较发达地区。

* 国家
  氏族、胞族和部落的社会形态形成是自然的，而随着发展，逐渐出现了超出氏族能力范围外的事务，随之氏族开始瓦解，国家随之出现，与私权相对立的公权出现，有三种经典的形式：
  + 希腊 - 随着商业的发展，不同氏族的人开始居住在同一个地区，原来适用于氏族的制度不再适用于这种情况。于是，中央机关出现了，不属于氏族的机构一出现，氏族便开始瓦解，国家开始出现
  + 罗马 - 罗马对外的征服，大量被释奴隶组成的平民阶级和原氏族贵族阶级间的矛盾出现，这些平民是独立在氏族外的，因此，需要一个公共的机构来处理这些矛盾
  + 德意志 - 德意志征服罗马，大量的土地落入了由军事领袖和扈从组成的独立于氏族的武装力量手中，也是王权的开始

  总的来说，都是随着社会的发展，原有氏族的制度不再适应现状，矛盾出现了并需要调和解决，国家是在这种背景下诞生出来的。

* 世袭
  在氏族制度时期，部落酋长虽然是选举出来的，但也形成了前任酋长亲属具备优先权的惯例。后面，随着社会发展，财富的分化，这种惯例逐渐变成了贵族的特权。

  关键的一点：随着生产力的发展，人们的生产出现了剩余，于是，部落中的其他人会将剩余作为礼物赠送给酋长，表示尊敬。

* 脉络
  野蛮时代：
  1. 原始群婚阶段，生产力较为落后，人口是极其稀少的，男女的分工是自然形成的。男性负责作战、打猎获取食物的原料，并制作为此所必须的工具。女性管家，负责衣食。男女分别是自己领域的主人，也是各自制造的工具的所有者。
     而家庭的财产是共有的。

     这时，男女生产力无大的差距，建立了基于母系血缘关系上的母权社会（但并不是说女性会是部落酋长，酋长依然有对外的男性担任）。

  2. 第一次分工，游牧部落的出现，使得「交换」变得频繁。同时牧畜的发展，也带动了农业的发展。一切部门——畜牧业、农业、家庭手工业——中生产的增加，使人的劳动力能够生产出超过维持劳动力所必需的产品。同时，这也增加了氏族、家庭公社或个体家庭的每个成员所担负的每日的劳动量。吸收新的劳动力成为人们向往的事情了。战争提供了新的劳动力：俘虏变成了奴隶。

     第一次社会大分工，在使劳动生产率提高，从而使财富增加并且使生产领域扩大的同时，在既定的总的历史条件下，必然地带来了奴隶制。从第一次社会大分工中，也就产生了第一次社会大分裂，分裂为两个阶级：主人和奴隶、剥削者和被剥削者。
  
     同时，随着生产力的发展，男性拥有的财产变多了，无论是牧畜还是战争，都是男性负责的，因此，女性在公共事务中的比重变少了。群婚逐渐往对偶、专偶发展，母权社会转向父权社会。
     
  3. 第二次大分工：手工业和农业分离了。随着生产分为农业和手工业这两大主要部门，便出现了直接以交换为目的的生产，即商品生产；随之而来的是贸易，不仅有部落内部和部落边境的贸易，而且海外贸易也有了。除了自由民和奴隶的差别以外，又出现了富人和穷人的差别。

     而住得日益稠密的居民，对内和对外都不得不更紧密地团结起来。按照氏族划分逐渐变成由地区划分，氏族制度的机关逐渐挣脱了自己在民族中，在氏族、胞族和部落中的根子，转化为自己的对立物：
     它从一个自由处理自己事务的部落组织转变为掠夺和压迫邻近部落的组织，而它的各机关也相应地从人民意志的工具转变为独立的、压迫和统治自己人民的机关了。

  总结：在野蛮时代低级阶段，人们只是直接为了自身的消费而生产；在野蛮时代中级阶段，游牧民族已经有牲畜作为财产，这种财产，到了畜群具有相当规模的时候，就可以经常提供超出自身消费的若干余剩；野蛮时代高级阶段，又进一步发生了农业和手工业之间的分工，于是劳动产品中日益增加的一部分是直接为了交换而生产的。
  
  文明时代：
  1. 文明时代巩固并加强了所有这些已经发生的各次分工，此外它又加上了一个第三次的、它所特有的、有决定意义的重要分工：它创造了一个不再从事生产而只从事产品交换的阶级——商人。
  2. 随着这个阶级的形成，出现了金属货币即铸币，随着金属货币就出现了非生产者统治生产者及其生产的新手段。
  3. 除了表现为商品和奴隶的财富以外，除了货币财富以外，这时还出现了表现为地产的财富。土地现在可以成为出卖和抵押的商品了。
  4. 随着贸易的扩大，随着货币和货币高利贷、土地所有权和抵押的产生，财富便迅速地积聚和集中到一个人数很少的阶级手中，与此同时，大众日益贫困化，贫民的人数也日益增长。
  5. 氏族制度面对着没有它的参与而兴起的新因素，它显得软弱无力。氏族制度的前提，是一个氏族或部落的成员共同生活在纯粹由他们居住的同一地区中。
  6. 于是产生了这样一个社会，它由于自己的全部经济生活条件而必然分裂为自由民和奴隶，进行剥削的富人和被剥削的穷人，而这个社会不仅再也不能调和这种对立，反而必然使这些对立日益尖锐化。一个这样的社会，只能或者存在于这些阶级相互间连续不断的公开斗争中，或者存在于第三种力量的统治下，这第三种力量似乎站在相互斗争着的各阶级之上，压制它们的公开的冲突，顶多容许阶级斗争在经济领域内以所谓合法形式决出结果来。氏族制度已经过时了。它被分工及其后果即社会之分裂为阶级所炸毁。它被国家代替了。

  脉络：生产力的发展，剩余的出现提高了劳动力的价值，使得第一次阶级分化出现：主人和奴隶。生产力的进一步发展和分工的细化，出现了直接以交换为目的的生产，即商品生产。随之而来的是贸易。直到创造了一个不再从事生产而只从事产品交换的阶级——商人，富人和穷人阶级出现。
  以生产力的发展为线索，串联了全书中关于婚姻形式、氏族到国家的演变过程。

* 摘抄
  国家是阶级矛盾不可调和的产物：
  #+begin_quote
  国家是社会在一定发展阶段上的产物；国家是承认：这个社会陷入了不可解决的自我矛盾，分裂为不可调和的对立面而又无力摆脱这些对立面。而为了使这些对立面，这些经济利益互相冲突的阶级，不致在无谓的斗争中把自己和社会消灭，就需要有一种表面上凌驾于社会之上的力量，这种力量应当缓和冲突，把冲突保持在“秩序”的范围以内；这种从社会中产生但又自居于社会之上并且日益同社会相异化的力量，就是国家。
  #+end_quote

  女权：
  #+begin_quote
  只要妇女仍然被排除于社会的生产劳动之外而只限于从事家庭的私人劳动，那么妇女的解放，妇女同男子的平等，现在和将来都是不可能的。妇女的解放，只有在妇女可以大量地、社会规模地参加生产，而家务劳动只占她们极少的工夫的时候，才有可能。而这只有依靠现代大工业才能办到，现代大工业不仅容许大量的妇女劳动，而且是真正要求这样的劳动，并且它还力求把私人的家务劳动逐渐溶化在公共的事业中。
  #+end_quote

  讽刺：
  #+begin_quote
  凡对统治阶级是好的，对整个社会也应该是好的，因为统治阶级把自己与整个社会等同起来了。所以文明时代越是向前进展，它就越是不得不给它所必然产生的种种坏事披上爱的外衣，不得不粉饰它们，或者否认它们——一句话，即实行流俗的伪善，这种伪善，无论在较早的那些社会形式下还是在文明时代初期阶段都是没有的，并且最后在下述说法中达到了极点：剥削阶级对被压迫阶级进行剥削，完全是为了被剥削阶级本身的利益；如果被剥削阶级不懂得这一点，甚至想要造反，那就是对行善的人即对剥削者的一种最卑劣的忘恩负义行为。
  #+end_quote

