:PROPERTIES:
:ID:       49fd7e00-7701-4815-b06d-be96df8181f0
:END:
#+TITLE: 封建

参考[[https://baike.baidu.com/item/%E5%B0%81%E5%BB%BA%E7%A4%BE%E4%BC%9A/24324#11][封建社会 - 名词争议 - 百度百科]]一节可知，封建在现在通常有两种语义：
+ 指政治制度 - 由共主或中央王朝给王室成员、王族和功臣分封领地，是一种「国家管理制度」而不是一种「社会」
+ 指社会形态 - 指地主或领主占有土地并剥削农民或农奴的社会形态

在政治制度上，我国早在秦朝便建立了中央集权的国家，后面汉武帝时期的[[https://baike.baidu.com/item/%E6%8E%A8%E6%81%A9%E4%BB%A4?fromModule=lemma_search-box][推恩令]]更是进一步巩固的中央集权，从此中国便进入了长达两千年的君主专制下封建社会。

在社会形态上，封建社会的主要生产资料是土地，主要特点就是拥有土地的地主或领主可以对依附于土地的农民和农奴进行剥削。

* 问题
  封建社会由于土地是主要生产资料，在新朝代建立后往往就会开始漫长的土地兼并过程，整个社会就会逐渐走向不平衡，遇到天灾人祸，农民活不下去了，就起义重开。

* 中欧封建区别
  欧洲中世纪是封建政治制度 + 封建社会形态，经济形态以「庄园经济」为主，庄园经济相对小农经济抗打击能力会更强，同时也是一种集体生产的模式（感觉为后来资本主义的生产模式提供了基础）。

  另外由于政治制度也是封建制度，向下领主对领地内的事务具有更强的管控能力，农民起义会更加困难。向上君主的权力相对分散，因此 1215 年英格兰贵族联盟打败君主签署了《大宪章》，
  在人类史上开创性地通过法律约束了国王的权力。

  中国古代是君主专制政治制度 + 封建社会形态，由于身处的地缘环境，使得自给自足更加容易，因此经济形态也以「小农经济」为主，小农经济以家庭为基本单位，也能更好调动农民积极性。

  稳定的君主专制王朝，按照现代国家的定义，中国当时的政治制度应该是全世界最先进的，相应地古代中国经济领跑全世界。

  但可惜，同时重农抑商，王朝更替往往也只是土地的再分配，没带来生产关系上的变化。

  也许，如果没有重农抑商的政策，中国说不定能比欧洲更快地进入资本主义阶段。但是在君主专制和各种原因的影响下，王朝统治真的太稳定了，向其他方向发展的速度也大大减缓或者被抑制了。

* 和资本主义区别
  封建社会生产资料破坏成本低，生产资料主要是土地，土地很难被破坏，而获得土地的方式基本上只能通过战争。

  资本主义相反，发动战争会破坏原材料供应和市场，因此其往往会选择非战争方式或是有限战争来达到目的。

  资本主义对封建社会的生产关系进行了破坏，从而在新的生产关系上建立了新的制度。

* 资本主义问题
  资本主义和封建一样，没有解决长期发展后带来的不平衡问题，只不过资本主义的生产关系变化，生产力的解法，工业革命带来的巨大生产力提升等，都推迟了由不平衡带来的矛盾问题。

  社会主义通过公有制进行再分配，可以解决不平衡问题。但相应存在官僚主义垄断、无法调动生产积极性等问题。

  欧洲现在一些国家民主社会主义政党便通过公共福利进行再分配（好像是？）。

