:PROPERTIES:
:ID:       ff47b9a9-8a79-465d-8f73-1027817bbbc8
:END:
#+TITLE: 形而上和形而上学
#+filetags: :philosophy:

* 形而上
  形而上（metaphysical）的翻译源自《易经》中的「形而上者谓之道，形而下者谓之器」这句话，「道」本身是一个抽象的概念，是宇宙的本源，形而上的本体，超越一切世间存在。

  和形而下的事物本身相对，形而上和形而下对应本源、本体和器物、现象的关系。

  在生活中，说 xx 形而上，也就是说 xx 一定程度了超越了事物本身，更接近抽象的概念，对本质的解释。

  参考：
  + [[https://zh.wikipedia.org/wiki/%E9%81%93][道 - 维基百科，自由的百科全书]]
  + [[https://baike.baidu.com/item/%E5%BD%A2%E8%80%8C%E4%B8%8A/65485][形而上（哲学名词）_百度百科]]

* 形而上学
  形而上学（metaphysics）是指对世界本质的研究，即研究一切存在者，一切现象（尤其指抽象概念）的原因及本源。最早由亚里士多德所构建，称其为“第一哲学”、“第一科学”。

  即研究形而上的问题的学问。

  形而上学试图阐明人们用以理解世界的基本概念（范畴），例如存在、客体（objects）及其性质、空间和时间、因果和可能性。

  参考：
  + [[https://baike.baidu.com/item/%E5%BD%A2%E8%80%8C%E4%B8%8A%E5%AD%A6/211789][形而上学（哲学的一个门类）_百度百科]]
  + [[https://zh.wikipedia.org/zh-hans/%E5%BD%A2%E4%B8%8A%E5%AD%B8][形上学 - 维基百科，自由的百科全书]]

* 马克思主义哲学（唯物辩证法）对形而上学的批判
  形而上学研究抽象、思辨的问题，而马克思主义哲学把现实的人作为哲学研究的出发点，把现实的人的生存境遇与发展命运作为哲学研究的主题，把人的解放、人的能力的充分发挥和每个人自由而全面发展作为追寻的价值目标。

  简单来说马克思主义的落脚点是现实的，辩证的。

  在《[[id:dbcb0f06-b0ed-4b79-8021-0a7ff74b9bd3][唯物辩证法大纲]]》中有提到：
  #+begin_quote
  形而上学认为事物是孤立的，静止的，内部也不存在矛盾。事物只有量的变化没有质的变化，同时将事物变化的原因归结为外部力量的推动。
  #+end_quote

  感觉这主要是因为形而上学研究的是抽象的问题，寻求终极的答案。而终极的答案，往往就是不变的，固定的东西。和辩证法认为事物是普遍联系发展的观点不同。

