:PROPERTIES:
:ID:       2a3882fb-fa2e-4d2d-8f2a-be4f02bef64e
:END:
#+TITLE: 美联储加息和缩表
#+filetags: :Economy:

#+begin_quote
货币是央行的负债，央行的资产负债表必须均衡。要释放出更多的货币，是需要更多的资产的，而不是凭空捏造的。
#+end_quote

缩表就是减少负债，也就是说会减少市场中流通的货币，这就可能导致经济发展的变慢，通缩，而建立在信贷基础上的经济周期就可能遇到[[id:6dc1904b-457e-43b2-a136-60fd858f3f17][明斯基时刻]]，也就是说，
一般来说是不会缩表的，除非通胀过高或存在其他问题，比如要戳破泡沫出清的时候。

而负债和资产是挂钩的，我们持有的货币可以在需要的时候兑换为央行持有的资产。在我国，央行的主要资产是外汇。外汇（资产）的增加可以释出更多的人民币，
带动国内经济的增长。


美联储加息，意味着美元的升值，会让人们更愿意储蓄美元，减小杠杆，也就是导致美元缩表。此时，以美元为主要资产的人民币就会贬值，此时就会导致：
#+begin_quote
人民币贬值会导致人们更愿意将人民币换成美元保值，导致央行外汇储备减少，导致人民币跟着缩表，直到汇率重新稳定
#+end_quote

但如果不想缩表怎么办？

美联储之前的一次加息周期为 2015-2018 年，基准利率从 0.25% 上调到 2.5%，但这个时间段国内并没有缩表，央行的外汇储备是下降了，但是央行的负债还在跟着涨，
正常来说之前央行的资产和负债比例是很稳定的，但这次加息周期中资产减少了，负债却增加了。

为什么呢？因为印了很多的钞票，涨价去库存，负债转移到居民部门（资产从外汇转为居民负债）：
#+begin_quote
因为美联储缩表，由美元派生的软妹币太多，为了让汇率不至于完蛋，这轮房价高涨是让那些不是自己人的人去接盘，将软妹币锁住，让汇率保持稳定（让人民币不贬值），然后再锁住房地产价格不再上涨，相当于央妈缩表，但最终受损的是那些高位接盘的借贷者。

2017-04-08
#+end_quote

再摘抄下看到的几个评论：
#+begin_quote
可不可以这样理解：
1. 稳房价（当前的政治任务）：即使不准交易也要把房价稳住，就是稳住接盘的人，让他们的账面资产看起来比较美，相当于乐视网的股票一直停牌，就是不交易。但是你按照这个房价去抵押贷款啥的就不行了。
2. 降杠杆（也是政治任务）：在房价不降的情况下，通过一些技巧，比如限制换汇、限制房屋抵押。把房地产变成一个死的资产，无法让他去进行信用扩张。等时间长了，杠杆慢慢就降下来了？

所以未来的情况是房价不准降，但是房子的附加价值（学区房、落户啥的）会被政策所稀释，政府会打开一个比较大的租房市场，提供租售同权这样的政策，提高租金。给高位站岗又手握多套房子的人补血，让他们不至于还不上贷款。

2017-09-21
#+end_quote

啧……

参考：
+ [[https://zhuanlan.zhihu.com/p/26027538][缩表是什么鬼？ - 知乎]]
+ [[https://zhuanlan.zhihu.com/p/21263798][关于货币最简单的逻辑 - 知乎]]

  
