:PROPERTIES:
:ID:       dbcb0f06-b0ed-4b79-8021-0a7ff74b9bd3
:ROAM_ALIASES: 唯物辩证法
:END:
#+TITLE: 辩证法唯物论
#+filetags: :philosophy:

* 目录                                                    :TOC_4_gh:noexport:
- [[#哲学的基本问题][哲学的基本问题]]
  - [[#第一方面][第一方面]]
  - [[#第二方面][第二方面]]
- [[#辩证法与形而上学][辩证法与形而上学]]
- [[#研究的对象和一般特征][研究的对象和一般特征]]
- [[#物质运动空间与时间][物质、运动、空间与时间]]
- [[#世界的物质的统一性和发展的无限性][世界的物质的统一性和发展的无限性]]
- [[#唯物辩证法的规律][唯物辩证法的规律]]
  - [[#对立统一规律][对立统一规律]]
- [[#参考][参考]]

* 哲学的基本问题
  哲学的基本问题是思维与存在的关系，分为两个方面：
  1. 第一方面：思维与存在何为第一性的问题，唯物论认为存在是第一性的，思维是第二性的，唯心论与之相反
  2. 第二方面：思维能否正确地认识存在的问题，可知论认为思维能正确地认识存在，不可知论与之相反

** 第一方面
   唯物论认为存在是第一性的，物质决定意识，唯物辩证法相较于旧的唯物论进步的一点是：旧的唯物论在历史观上认为少数人决定了历史的走向，唯物辩证法纠正了这一错误的观点，认为社会存在决定社会意识。
   历史并不是由少数人决定的。这也被叫做历史唯物论。

   唯心论可以分为客观唯心论和主观唯心论两种：
   + 客观唯心论认为宇宙中存在一个「绝对意志」，世界上的一切都是这个绝对意志决定的
   + 主观唯心论认为客观世界是不存在的，存在的只是“我”的感觉、观念

   唯心论是错误的，但唯心论存在自身的认识论根源：
   1. 人们的意识是客观世界的主观映像，是被移植于人脑中并在人脑中被改造过的物质现象。意识的内容和泉源是客观的，意识的形式是主观的。当人们把认识过程中的「感觉」夸大为脱离物质的东西时，就是主观唯心论。
      当人们把认识过程中的「概念」夸大为脱离物质的东西时，就是客观唯心论。
   2. 人们对客观世界的反映是积极的，能动的，能够运用到改造客观世界当中。如果把意识的能动作用夸大到不受物质约束的程度，否定了意识是存在的反映，就会陷入唯心论。这是一切唯心论的共同基础。

** 第二方面
   思维能否正确地认识存在的问题，也叫做思维和存在的同一性问题。可知论认为思维能正确地认识存在，唯物论必然是可知论。辩证法唯物论相较于旧唯物论进步的是：
   1. 指出实践是思维和存在同一性的基础，实践是检验思维是否符合现实的唯一标准
   2. 将辩证法运用于唯物论。旧唯物论认为思维对存在的反映是僵死的、不动的、一次完成的。而实际上认识是不断加深的，是一个由浅到深的过程

   唯心论也有可知论，但最后往往会走到不可知论去。

* 辩证法与形而上学
  基于对发展的观点的不同可以分为辩证法与形而上学，辩证法认为事物是普遍联系的，事物是发展的，有量的变化也有质的变化，同时认为事物内部也存在矛盾，矛盾普遍存在。事物运动的根因源自事物内部。
  形而上学与之相反，认为事物是孤立的，静止的，内部也不存在矛盾。事物只有量的变化没有质的变化，同时将事物变化的原因归结为外部力量的推动。

  辩证法并不否定外部力量的作用，但认为外因只是事物变化的条件，外因只有通过内因起作用。

  典型的矛盾观点：
  1. 关于社会变化的原因：形而上学、庸俗进化论总是用地理环境、气候等外部因素来解释，不是从社会内部原因来解释
  2. 关于人性：形而上学认为人性从古至今都是一样的，没有变化。人性本恶、人性本贪便属于形而上学的观点。在唯物辩证法中认为人性是一切社会关系的总和，人性受到社会关系的影响。

* 研究的对象和一般特征
  哲学在最初的时候是当时一切知识的总和，即包含了世界观的问题，也包含了后来产生的专门学科研究的问题。随着生产斗争和阶级斗争的发展，越来越多的问题从哲学中分化出去成为专门的学科，比如数学、物理、化学、社会科学等等。
  最后，除了关于思维的学说（辩证法和形式逻辑，形式逻辑不属于哲学），其余一切关于自然和社会的学说都归属于各门实证科学之中了。

  但是各中专门科学都是研究特殊领域中的特殊规律的，不是研究世界最一般规律的。而唯物辩证法研究的便是关于外部世界和人类思维运动的一般规律的科学。

  考察发现一般规律在界所特有的表现就是自然辩证法，在社会历史中特有的表现就是历史辩证法（唯物史观）。

  一般特征为：唯物论和辩证法的统一、科学的世界观和方法论的统一、理论和实践统一、阶级性和科学性统一。

* 物质、运动、空间与时间
  在辩证法唯物论中，物质的范畴为：离开意识而独立又能为意识所反映的「客观实在」。需要注意区分物质的范畴、物质的结构和物质的形态。物质的范畴是固定的，但对物质的结构的认识是不断加深的，物质的形态是不断变化的。

  关键的一点是：物质的物理特性和物质是否存在于意识之外是两个不同的问题。关于量子力学中的观察者效应和物质的统一性问题 ☞ [[id:7d86af39-ce4c-4f57-9cd7-6040734b583a][双缝干涉实验和观察者效应]]。
  
  而物质和运动是不可分割的，物质是运动的主体，而运动是物质的存在形式和固有属性。没有离开运动的物质，也没有离开物质的运动。运动是绝对的，静止是相对的。认为运动是主体的是[[id:d056a180-f9bc-428c-bbb6-9072e6907e5a][唯能论]]。

  运动的基本形式按照当前的科学水平可以分为：
  1. 客体在空间中的位置变动（这是力学的研究对象）
  2. 波和粒子的运动（这是物理学的研究对象)
  3. 原子的化合和分解运动（这是化学的研究对象)
  4. 有机体的运动，即同化与异化、遗传与变异（这是生物学的研究对象)
  5. 社会运动，即生产力和生产关系、基础和上层建筑的发展变化（这是社会科学的研究对象）

  这些运动形式不是彼此孤立，而是相互依存的：
  1. 高级运动形式依赖于低级运动形式，它是在低级运动形式的基础上产生、并把低级运动形式包括在自己之内。
  2. 低级运动形式当其作为高级运动形式的基础而被包括在高级运动形式之内时，它的作用也依赖于高级运动形式。
  3. 各种运动形式可以在一定的条件下互相转化。从宇宙发展的长河看，各种运动形式是按照由低级到高级，由简单到复杂的秩序逐步展开的。

  其次，各种运动形式固然是互相依存的，但又是本质上互相区别的。唯物辩证法不允许把不同质的运动形式混清起来，不允许把高级的运动形式归结为低级的运动形式。
  当然，高级运动形式总是包括着低级运动形式，但是低级运动形式在高级运动形式中并不起主导的、决定的作用，而只起辅助的、次要的作用。高级运动形式之所以为高级运动形式，并不是因为它包括着低级运动形式， 而是因为它具有自己的质的特殊性。

  [[https://zh.wikipedia.org/wiki/%E7%A4%BE%E4%BC%9A%E8%BE%BE%E5%B0%94%E6%96%87%E4%B8%BB%E4%B9%89][社会达尔文主义]]便是使用生物学的规律去解释社会现象得到的。
  
  同时，运动是守恒的，任何运动都不会从乌有中产生，也不会转化为乌有，客观存在着的是各种运动形式之间相互转化的无限过程：
  1. 任何一种运动形式在转化为别种运动形式的时候，运动的总量是不变的。这是这个原理的量的方面。
  2. 任何一种运动形式，都具有转化为别种运动形式的永不丧失的能力。这是这个原理的质的方面。

  这里不能只从数量上去把握，而且还必须从质量上去理解。

  而空间和时间是运动着的物质的存在形式，正像运动与物质是不可分割的一样，空间和时间与物质也是不可分割的：
  1. 没有离开空间和时间的物质。
  2. 没有离开物质的空间和时间。空间和时间是物质的存在形式，是以物质为内容的，相对论证明了空间和时间的待性也是随着物质形态的变化而变化的。

     绝对时空观：空间是贮藏物质的空虚的“容器”，时间是绝对均匀流逝的持续性，二者都是与物质过程无关的独立实体。空间和时间的特性是绝对不变的，空间的特性服从于欧几里得几何学，时间的特性则服从于数序规律。这样理解的空间和时间叫做“绝对空间”和“绝对时间”。
     而实际上相对论已经说明了空间和时间会受到物质的影响。

  同时，唯物辩证法认为物质世界是无限的，因而作为物质的存在形式的空间和时间也是无限的。宇宙无所谓边际，宇宙无所谓始终。如果承认空间和时间有限，那么边界外的就只能是非物质的东西了，就容易引入上帝的存在。比如时间的开始因为上帝啥的。

  PS: 这里得出空间和时间的无限性的方式感觉很牵强，虽然常识不一定正确，有限还是无限现在人类都没法证明。但如果承认有限，那么边界外的东西确实就很唯心了。

  而空间和时间的区别在于，它们是物质的两种不同的存在形式，空间是三维的，时间是一维的。

  PS: 书中这里不承认多维空间。感觉这篇文章[[https://zhuanlan.zhihu.com/p/59497506][科学解读：什么是时间？什么是空间？理论上时空是什么？ - 知乎]]里的定义更好：
  + 时间就是量子尺度上可计数的状态变化
  + 空间就是物质变化的呈现
  + 时间与空间都是源于物质的变化，于是时间与空间，就（通过物质变化）一起构成了——紧密联系不可分割的时空，并且时空与物质，就像是一个统一的整体，是一个共同的本质，所呈现的不同表象。

* 世界的物质的统一性和发展的无限性
  物质的统一性：
  1. 整个自然界，从宏观世界到微观世界，从无机世界到有机世界，都是统一于物质的。
  2. 人类社会是物质世界的高级发展阶段，唯物史观指出，人类社会的基础是人们在生产物质生活资料的过程中所结成的生产关系。这种生产关系是不依任何人的意识为转移的物质的关系。

  发展的无限性：
  1. 一切现存的事物，包括人们的意识在内，都是这个统一的物质世界长期发展的产物；物质世界的发展不是简单的循环和重复，而是由低级到高级、由简单到复杂的无限过程。

  意识是物质世界发展到一定阶段的产物：
  1. 由低级的反映形式到高级的反映形式的发展，从无机的物理或化学的反映，到生物对刺激的反映，到非条件反射和条件反射。
  2. 意识是人脑的机能，除了接受现实刺激物的刺激而引起条件反射的一套神经活动，还有更高级的接受语言刺激而引起条件反射的一套神经活动。从感性认识到概念认识。语言是思维的直接现实，是思维的自然物质。
     意识决不是什么同物质并列的独立的实体，更不是物质世界的创造主；恰恰相反，它仅仅是物质世界发展到一定阶段的产物，仅仅是一种特殊的物质（人脑）的机能或属性，仅仅是物质世界在人脑中的反映，它是一点也不能离开物质的。
  3. 意识对物质世界有反作用，但意识的能动作用不管有多么大，仍然不能不受物质世界的制约，不能超越客观物质条件所许可的范围。

  核心的观点就是：
  1. 物质决定意识，意识是物质的。延展到社会学就是生产力决定生产关系，经济基础决定上层建筑。意识有主观能动性，但也受限于物质基础。
  2. 物质是发展的，形而上的观点，不变或者只有量变没有质变是错误的。

* 唯物辩证法的规律
  物质世界的各个特殊领域中的现象的发展变化都服从于各自的特殊规律，而整个物质世界的发展变化又服从于一般规律，即普遍规律。前者是各门具体科学的研究对象，后者是唯物辩证法的研究对象。

  任何事物不仅受普遍规律的支配，而且受特殊规律的支配。只懂得普遍规律而不懂得特殊规律，还是不能把具体工作做好。如果以为一个人只要学了唯物辩证法的规律，就既会种地，又会做工，既会打仗，又会治病，成为无所不能的万事通，那是错误的。
  
  唯物辩证法不是包医百病的现成药方，而是指导我们研究具体事物的工具。
  
** 对立统一规律
  ☞ [[id:3c6d6981-2f4a-42b8-8f80-5da12b25bdc6][矛盾论]]
  
  1) 对立统一规律是辩证法最根本的规律，其他辩证法的规律和范畴都是对立统一规律在不同方面的表现形态
  2) 唯物辩证法从来不把矛盾的同一性解释为矛盾双方的“共同点”或“共同要求”，也从来不把矛盾双方的同一性说成只是不可分离地联系着的意思，相反，它认为矛盾同一性的更加重要的意义是矛盾双方能够而且必然在一定的条件下向着自已对方所处的地位转化（也就是事物能够质变）

* 参考
  + 《唯物辩证法大纲 - 李达》

