:PROPERTIES:
:ID:       dbcb0f06-b0ed-4b79-8021-0a7ff74b9bd3
:END:
#+TITLE: 辩证法唯物论
#+filetags: :Philosophy:

* 实践论
  人对世界的认识源自实践，最初得到的认识属于感性的认识。随着对事物认识的增加，会逐渐得到理性的认识。

  理性认知是否正确需要在在实践中运用才能得出结论。

  「实践 -> 理论 -> 实践」是一个循序渐进的过程。

  只关注理论不关注实践，是教条主义。而只关注实践经验不注重理论的提炼，是经验主义。
  
* 矛盾论
  在辩证法唯物论中，矛盾指「事物内部对立统一」这一性质，矛盾普遍存在，但不同事物又存在有各自特殊的矛盾。

  事物的基本矛盾决定事物的根本性质并在事物运动发展的全过程中起支配作用，主要矛盾决定事物当前阶段的性质，
  规定或影响着其他矛盾的存在和发展。

  矛盾中有存在着占优势的主要矛盾方面，反之是次要矛盾方面。

  矛盾的基本属性是同一性和斗争性，同一是相对的，矛盾的两方面在「一定条件」下可以互相转换。矛盾的两方面也互相依存。
  而斗争是绝对的，斗争为事物的发展创造了条件，矛盾的解决只有通过斗争性才会成为现实，
  只有矛盾斗争性才能突破事物原有的极限。

** 基本矛盾和主要矛盾
   事物的基本矛盾，或者说根本矛盾，决定了事物的根本性质并在事物运动发展的全过程中起支配作用。

   在复杂事物发展的发展过程中，有很许多矛盾存在，其中必然有且只有一种是主要矛盾，它的存在和发展规定或影响着其他矛盾的存在和发展。

   两者区别：
   + 基本矛盾贯彻事物发展始终，决定了事物的根本性质并在事物运动发展的全过程中起支配作用
   + 主要矛盾决定事物当前阶段的性质，事物不同发展阶段的主要矛盾可能不同

   比如人类社会的基本矛盾是生产力和生产关系、经济基础和上层建筑间的矛盾，而处于不同的发展阶段时，比如资本主义社会和社会主义社会，
   社会的基本矛盾依然没变，但是主要矛盾发生了变化。

   社会依然是社会，基本矛盾没变。而主要矛盾的不同决定了资本主义社会和社会主义社会性质的不同。


* 参考
  + 《实践论》《矛盾论》导读（增订版）
  + [[https://www.marxists.org/chinese/maozedong/1937/index.htm][毛泽东：辩证法唯物论（讲授提纲）（中国人民解放军政治学院训练部 翻印本）]]
  + [[https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193707.htm][实践论：论认识和实践的关系——知和行的关系（一九三七年七月）]]
  + [[https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193708.htm][矛盾论（一九三七年八月）]]

