:PROPERTIES:
:ID:       dbcb0f06-b0ed-4b79-8021-0a7ff74b9bd3
:ROAM_ALIASES: 唯物辩证法
:END:
#+TITLE: 辩证法唯物论
#+filetags: :Philosophy:

* 目录                                                    :TOC_4_gh:noexport:
- [[#哲学的基本问题][哲学的基本问题]]
  - [[#第一方面][第一方面]]
  - [[#第二方面][第二方面]]
- [[#辩证法与形而上学][辩证法与形而上学]]
- [[#研究的对象和一般特征][研究的对象和一般特征]]
- [[#实践论和矛盾论][《实践论》和《矛盾论》]]
  - [[#实践论][实践论]]
  - [[#矛盾论][矛盾论]]
    - [[#基本矛盾和主要矛盾][基本矛盾和主要矛盾]]
  - [[#参考][参考]]

* 哲学的基本问题
  哲学的基本问题是思维与存在的关系，分为两个方面：
  1. 第一方面：思维与存在何为第一性的问题，唯物论认为存在是第一性的，思维是第二性的，唯心论与之相反
  2. 第二方面：思维能否正确地认识存在的问题，可知论认为思维能正确地认识存在，不可知论与之相反

** 第一方面
   唯物论认为存在是第一性的，物质决定意识，唯物辩证法相较于旧的唯物论进步的一点是：旧的唯物论在历史观上认为少数人决定了历史的走向，唯物辩证法纠正了这一错误的观点，认为社会存在决定社会意识。
   历史并不是由少数人决定的。这也被叫做历史唯物论。

   唯心论可以分为客观唯心论和主观唯心论两种：
   + 客观唯心论认为宇宙中存在一个「绝对意志」，世界上的一切都是这个绝对意志决定的
   + 主观唯心论认为客观世界是不存在的，存在的只是“我”的感觉、观念

   唯心论是错误的，但唯心论存在自身的认识论根源：
   1. 人们的意识是客观世界的主观映像，是被移植于人脑中并在人脑中被改造过的物质现象。意识的内容和泉源是客观的，意识的形式是主观的。当人们把认识过程中的「感觉」夸大为脱离物质的东西时，就是主观唯心论。
      当人们把认识过程中的「概念」夸大为脱离物质的东西时，就是客观唯心论。
   2. 人们对客观世界的反映是积极的，能动的，能够运用到改造客观世界当中。如果把意识的能动作用夸大到不受物质约束的程度，否定了意识是存在的反映，就会陷入唯心论。这是一切唯心论的共同基础。

** 第二方面
   思维能否正确地认识存在的问题，也叫做思维和存在的同一性问题。可知论认为思维能正确地认识存在，唯物论必然是可知论。辩证法唯物论相较于旧唯物论进步的是：
   1. 指出实践是思维和存在同一性的基础，实践是检验思维是否符合现实的唯一标准
   2. 将辩证法运用于唯物论。旧唯物论认为思维对存在的反映是僵死的、不动的、一次完成的。而实际上认识是不断加深的，是一个由浅到深的过程

   唯心论也有可知论，但最后往往会走到不可知论去。

* 辩证法与形而上学
  基于对发展的观点的不同可以分为辩证法与形而上学，辩证法认为事物是普遍联系的，事物是发展的，有量的变化也有质的变化，同时认为事物内部也存在矛盾，矛盾普遍存在。事物运动的根因源自事物内部。
  形而上学与之相反，认为事物是孤立的，静止的，内部也不存在矛盾。事物只有量的变化没有质的变化，同时将事物变化的原因归结为外部力量的推动。

  辩证法并不否定外部力量的作用，但认为外因只是事物变化的条件，外因只有通过内因起作用。

  典型的矛盾观点：
  1. 关于社会变化的原因：形而上学、庸俗进化论总是用地理环境、气候等外部因素来解释，不是从社会内部原因来解释
  2. 关于人性：形而上学认为人性从古至今都是一样的，没有变化。人性本恶、人性本贪便属于形而上学的观点。在唯物辩证法中认为人性是一切社会关系的总和，人性受到社会关系的影响。

* 研究的对象和一般特征
  哲学在最初的时候是当时一切知识的总和，即包含了世界观的问题，也包含了后来产生的专门学科研究的问题。随着生产斗争和阶级斗争的发展，越来越多的问题从哲学中分化出去成为专门的学科，比如数学、物理、化学、社会科学等等。
  最后，除了关于思维的学说（辩证法和形式逻辑，形式逻辑不属于哲学），其余一切关于自然和社会的学说都归属于各门实证科学之中了。

  但是各中专门科学都是研究特殊领域中的特殊规律的，不是研究世界最一般规律的。而唯物辩证法研究的便是关于外部世界和人类思维运动的一般规律的科学。

  运用于自然研究就是自然辩证法，运用于考察历史社会就是历史辩证法（唯物史观）。

  一般特征为：唯物论和辩证法的统一、科学的世界观和方法论的统一、理论和实践统一、阶级性和科学性统一。

* 《实践论》和《矛盾论》
** 实践论
   :PROPERTIES:
   :ID:       184069db-12a6-4805-973c-41a21e508eba
   :END:
   人对世界的认识源自实践，最初得到的认识属于感性的认识。随着对事物认识的增加，会逐渐得到理性的认识。

   理性认知是否正确需要在在实践中运用才能得出结论。

   「实践 -> 理论 -> 实践」是一个循序渐进的过程。

   只关注理论不关注实践，是教条主义。而只关注实践经验不注重理论的提炼，是经验主义。

** 矛盾论
   :PROPERTIES:
   :ID:       3c6d6981-2f4a-42b8-8f80-5da12b25bdc6
   :END:
   在辩证法唯物论中，矛盾指「事物内部对立统一」这一性质，矛盾普遍存在，但不同事物又存在有各自特殊的矛盾。

   事物的基本矛盾决定事物的根本性质并在事物运动发展的全过程中起支配作用，主要矛盾决定事物当前阶段的性质，规定或影响着其他矛盾的存在和发展。

   矛盾中有存在着占优势的主要矛盾方面，反之是次要矛盾方面。

   矛盾的基本属性是同一性和斗争性，同一是相对的，矛盾的两方面在「一定条件」下可以互相转换。矛盾的两方面也互相依存。而斗争是绝对的，斗争为事物的发展创造了条件，矛盾的解决只有通过斗争性才会成为现实，只有矛盾斗争性才能突破事物原有的极限。

   矛盾斗争的形式有很多种，其中对抗是较为特殊的一种，但并不是所有矛盾都会发展为对抗的形式。在资本主义社会中，阶级矛盾会发展为对抗的形式，但在社会主义中，阶级矛盾可以通过非对抗的斗争解决。

*** 基本矛盾和主要矛盾
    事物的基本矛盾，或者说根本矛盾，决定了事物的根本性质并在事物运动发展的全过程中起支配作用。

    在复杂事物发展的发展过程中，有很许多矛盾存在，其中必然有且只有一种是主要矛盾，它的存在和发展规定或影响着其他矛盾的存在和发展。

    两者区别：
    + 基本矛盾贯彻事物发展始终，决定了事物的根本性质并在事物运动发展的全过程中起支配作用
    + 主要矛盾决定事物当前阶段的性质，事物不同发展阶段的主要矛盾可能不同

    比如人类社会的基本矛盾是生产力和生产关系、经济基础和上层建筑间的矛盾，而处于不同的发展阶段时，比如资本主义社会和社会主义社会，社会的基本矛盾依然没变，但是主要矛盾发生了变化。

    社会依然是社会，基本矛盾没变。而主要矛盾的不同决定了资本主义社会和社会主义社会性质的不同。

** 参考
   + 《实践论》《矛盾论》导读（增订版）
   + [[https://www.marxists.org/chinese/maozedong/1937/index.htm][毛泽东：辩证法唯物论（讲授提纲）（中国人民解放军政治学院训练部 翻印本）]]
   + [[https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193707.htm][实践论：论认识和实践的关系——知和行的关系（一九三七年七月）]]
   + [[https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193708.htm][矛盾论（一九三七年八月）]]
