:PROPERTIES:
:ID:       056dc7c9-b518-4fc1-bcb4-4092684c23de
:END:
#+TITLE: 马克思主义和无政府主义
#+filetags: :politics:

在知乎上看到过的一个评论，说马克思还是恩格斯晚年是倾向于无政府的。结果一搜才发现，还真的有无政府主义，但马克思主义和无政府主义之间还存在矛盾。

按照恩格斯在[[id:46b581a6-f083-4273-a19a-af46f9a09eea][家庭、私有制和国家的起源]]中的观点，国家或者说公权和私权是对立的，是同社会相异化，凌驾在社会上的力量：
#+begin_quote
国家是社会在一定发展阶段上的产物；国家是承认：这个社会陷入了不可解决的自我矛盾，分裂为不可调和的对立面而又无力摆脱这些对立面。而为了使这些对立面，这些经济利益互相冲突的阶级，不致在无谓的斗争中把自己和社会消灭，就需要有一种表面上凌驾于社会之上的力量，这种力量应当缓和冲突，把冲突保持在“秩序”的范围以内；这种从社会中产生但又自居于社会之上并且日益同社会相异化的力量，就是国家。
#+end_quote

这样的描述看着就不是好东西，确实有点反对政府的意思。那为啥马克思主义和无政府主义之间还存在矛盾呢？

网上搜索了一些资料，目前的理解：
1. 通过[[id:b8f30185-a977-432a-ad3e-67a1cd2fc196][共产主义]]在维基百科上的词条，共产主义最终确实是「国家得到了废除的」。
   #+begin_quote
   共产主义是一种共享经济结合集体主义的政治思想，主张消灭生产资料私有制，并建立一个各尽所能、各取所需的生产资料公有制，进行集体生产，以阶级斗争建立无阶级的社会。在此一体系下，土地和资本财产为人民共同所有，而且货币和国家都得到了废除。
   #+end_quote

   但是这是在「高级阶段」，而在初级或中级阶段国家都还是存在的。

2. [[id:05fc0d6c-7848-44eb-817d-f618a7f6ed06][社会主义]]和[[https://zh.wikipedia.org/zh-hans/%E6%97%A0%E4%BA%A7%E9%98%B6%E7%BA%A7%E4%B8%93%E6%94%BF][无产阶级专政]]被认为是从废除资本主义迈向共产主义的过渡阶段，这个阶段无产阶级需要和资产阶级相斗争，国家在这个阶段是保障无产阶级利益的必要形式。

3. [[https://zh.wikipedia.org/zh-hans/%E6%97%A0%E6%94%BF%E5%BA%9C%E4%B8%BB%E4%B9%89][无政府主义]]反对所有强制性、胁迫性的阶级制度。认为国家政体有害，本身无存在必要。同时认为理论学习和发展是知识精英主义的帮凶，或只是某种的纸上谈兵。

#+begin_quote
后者主张立刻实行绝对的、全面的所谓“平等”，而马克思和恩格斯所提倡的，是在社会经济条件成熟之后的社会主义变革，而且在这一过程中也需要有无产阶级的国家权威来完成这一变革。巴枯宁所提倡的人人平等没有考虑到不同历史发展阶段的特点，他所鼓动和参与的暴动也没有考虑到政治运动本身是否具备合适的社会条件。
#+end_quote

简单来说，虽然马克思主义和无政府主义最终形态都是废除了国家，但是现阶段并不存在这样的条件，无政府主义过于激进，左中之左。

参考：
+ [[https://www.marxist.com/marxist-and-anarchist-theory-cn-simplified.htm][马克思主义与无政府主义理论 | Chinese | Other Languages]]
+ [[https://www.rccp.pku.edu.cn/mzyt/125153.htm][彭小瑜：马克思恩格斯对19世纪无政府主义宗教观的批判]]
+ [[https://www.marxists.org/chinese/stalin/mia-chinese-stalin-190606-07.htm][无政府主义还是社会主义？（斯大林，于1906年6—7月）]]

